name: pull-request

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  GIT_SHA_SHORT: $(echo ${{ github.sha }} | cut -c1-7)

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check PR integrity
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v1
        with:
          java-version: "14"
          architecture: x64

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      
      - run: |
          gcloud auth configure-docker
      
      - name: Build Docker Image
        run: |
          docker build -t eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking/functional-tests:latest .
          docker push eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking/functional-tests:latest
          docker tag eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking/functional-tests:latest eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking/functional-tests:${{ env.GIT_SHA_SHORT }}
          docker push eu.gcr.io/${{ secrets.DEV_REPO }}/securebanking/functional-tests:${{ env.GIT_SHA_SHORT }}

