name: merge-master
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  GIT_SHA_SHORT: $(echo ${{ github.sha }} | cut -c1-7)
  SERVICE_NAME: uk-functional-tests

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check Master integrity
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_CREDENTIALS_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      
      - run: |
          gcloud auth configure-docker
      
      - name: Build Docker Image
        run: |
          make docker tag=${{ env.GIT_SHA_SHORT }}
          docker tag eu.gcr.io/${{ secrets.GCR_DEV_REPO }}/securebanking/tests/${{ env.SERVICE_NAME}}:${{ env.GIT_SHA_SHORT }} eu.gcr.io/${{ secrets.GCR_DEV_REPO }}/securebanking/tests/${{ env.SERVICE_NAME}}:latest
          docker push --all-tags eu.gcr.io/${{ secrets.GCR_DEV_REPO }}/securebanking/tests/${{ env.SERVICE_NAME}}

