name: pull-request

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md

env:
  PR_NUMBER: pr-${{ github.event.number }}
  SERVICE_NAME: uk-functional-tests
  TEST_TASK: tests_v3_1_10

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check PR integrity
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCR_CREDENTIALS_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      
      - run: |
          gcloud auth configure-docker
      
      - name: Build Docker Image
        run: |
          make docker tag=${{ env.PR_NUMBER }}
      
      - name: 'Run Functional Tests'
        uses: codefresh-io/codefresh-pipeline-runner@master
        with:
          args: '-v SPEC_IMAGE=${{ env.SERVICE_NAME }} -v TAG=${{ env.PR_NUMBER }} -v TEST_TASK=${{ env.TEST_TASK }}'
        env:
          PIPELINE_NAME: 'ForgeCloud/sbat-infra/dev-functional-tests'
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          TRIGGER_NAME: github-actions-trigger-functionaltest
        id: run-tests
